version: "3.8"
services:
  static:
    build: 
      context: ./frontend
      dockerfile: static.Dockerfile
    ports: 
    - 3001:80
    volumes: 
    - ./frontend:/reactApp
    - /reactApp/node_modules
    depends_on: 
    - backend
  frontend:
    build: ./frontend
    ports: 
    - 3000:3000
    stdin_open: true
    volumes: 
    - ./frontend:/reactApp
    - /reactApp/node_modules
    depends_on: 
    - backend
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      DB_HOST: postgres_local
      API_KEY: foobar
      ENV: development
    volumes:
    - ./backend:/code
    ports:
    - 8000:8000
    depends_on:
    - db
  db:
    container_name: postgres_local
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes: 
    - ./backend/pgdump.sql:/docker-entrypoint-initdb.d/pgdump.sql