# Generated by Django 3.1.2 on 2020-10-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tri',
            fields=[
                ('year', models.IntegerField(blank=True, db_column='YEAR', null=True)),
                ('facilityname', models.TextField(blank=True, db_column='FACILITYNAME', null=True)),
                ('streetaddress', models.TextField(blank=True, db_column='STREETADDRESS', null=True)),
                ('city', models.TextField(blank=True, db_column='CITY', null=True)),
                ('county', models.TextField(blank=True, db_column='COUNTY', null=True)),
                ('st', models.TextField(blank=True, db_column='ST', null=True)),
                ('zip', models.IntegerField(blank=True, db_column='ZIP', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='LATITUDE', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='LONGITUDE', null=True)),
                ('parentconame', models.TextField(blank=True, db_column='PARENTCONAME', null=True)),
                ('industrysector', models.TextField(blank=True, db_column='INDUSTRYSECTOR', null=True)),
                ('chemical', models.TextField(blank=True, db_column='CHEMICAL', null=True)),
                ('cleanairactchemical', models.TextField(blank=True, db_column='CLEANAIRACTCHEMICAL', null=True)),
                ('classification', models.TextField(blank=True, db_column='CLASSIFICATION', null=True)),
                ('carcinogen', models.TextField(blank=True, db_column='CARCINOGEN', null=True)),
                ('unitofmeasure', models.TextField(blank=True, db_column='UNITOFMEASURE', null=True)),
                ('fugitiveair', models.IntegerField(blank=True, db_column='FUGITIVEAIR', null=True)),
                ('stackair', models.IntegerField(blank=True, db_column='STACKAIR', null=True)),
                ('totalreleaseair', models.IntegerField(blank=True, db_column='TOTALRELEASEAIR', null=True)),
                ('totalreleasewater', models.IntegerField(blank=True, db_column='TOTALRELEASEWATER', null=True)),
                ('totalreleaseland', models.IntegerField(blank=True, db_column='TOTALRELEASELAND', null=True)),
                ('on_sitereleasetotal', models.IntegerField(blank=True, db_column='ON-SITERELEASETOTAL', null=True)),
                ('off_sitereleasetotal', models.IntegerField(blank=True, db_column='OFF-SITERELEASETOTAL', null=True)),
                ('totalreleases', models.IntegerField(blank=True, db_column='TOTALRELEASES', null=True)),
                ('one_timerelease', models.TextField(blank=True, db_column='ONE-TIMERELEASE', null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'TRI',
            },
        ),
    ]
