# Generated by Django 3.1.1 on 2020-09-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tri2018',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, db_column='YEAR', null=True)),
                ('facilityname', models.TextField(blank=True, db_column='FACILITYNAME', null=True)),
                ('streetaddress', models.TextField(blank=True, db_column='STREETADDRESS', null=True)),
                ('city', models.TextField(blank=True, db_column='CITY', null=True)),
                ('county', models.TextField(blank=True, db_column='COUNTY', null=True)),
                ('st', models.TextField(blank=True, db_column='ST', null=True)),
                ('zip', models.IntegerField(blank=True, db_column='ZIP', null=True)),
                ('latitude', models.FloatField(blank=True, db_column='LATITUDE', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='LONGITUDE', null=True)),
                ('parentco', models.TextField(blank=True, db_column='PARENTCO', null=True)),
                ('industrysector', models.TextField(blank=True, db_column='INDUSTRYSECTOR', null=True)),
                ('chemical', models.TextField(blank=True, db_column='CHEMICAL', null=True)),
                ('cleanairact', models.TextField(blank=True, db_column='CLEANAIRACT', null=True)),
            ],
            options={
                'db_table': 'TRI_2018',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TRImodel',
        ),
    ]
