# Generated by Django 3.1.1 on 2020-09-30 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewModule', '0002_auto_20200929_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tri2018',
            options={},
        ),
    ]
